"""
Population Analysis Module

This module provides tools for extracting morphological and intensity-based features
from labeled objects in a segmented image. It is designed to work with segmentation
masks generated by tools like Cellpose or StarDist.

The primary class, PopulationAnalyzer, uses `skimage.measure.regionprops_table` for
efficient feature extraction, producing a pandas DataFrame where each row corresponds
to a single object (e.g., a cell) and each column represents a measured property.

This data forms the basis for statistical analysis, population comparisons,
and data visualization.
"""

import numpy as np
import pandas as pd
from skimage.measure import regionprops_table

class PopulationAnalyzer:
    """
    A class to perform population analysis on segmented images.
    It extracts morphological and intensity-based features for each
    labeled object in a segmentation mask.
    """

    def analyze(self, image: np.ndarray, mask: np.ndarray):
        """
        Performs population analysis on an image given a segmentation mask.

        Args:
            image (np.ndarray): The original image data (must be 2D).
            mask (np.ndarray): The 2D segmentation mask with labeled objects.

        Returns:
            dict: A dictionary containing the analysis results, with the following keys:
                  - 'status': 'success' or 'error'
                  - 'data': A pandas DataFrame with features for each object.
                  - 'message': A descriptive message.
        """
        if image.ndim != 2 or mask.ndim != 2:
             return {'status': 'error', 'message': 'Image and mask must be 2D arrays.'}

        if image.shape != mask.shape:
            return {'status': 'error', 'message': 'Image and mask must have the same dimensions.'}

        if mask.max() == 0:
            return {'status': 'error', 'message': 'Segmentation mask contains no labeled objects.'}

        try:
            # Define the properties to be measured
            properties = [
                'label', 'area', 'perimeter', 'eccentricity', 'orientation',
                'major_axis_length', 'minor_axis_length', 'solidity',
                'mean_intensity', 'max_intensity', 'min_intensity'
            ]

            # Use regionprops_table for efficient feature extraction
            props_table = regionprops_table(
                mask,
                intensity_image=image,
                properties=properties,
                cache=True
            )
            
            df = pd.DataFrame(props_table)

            # Calculate additional useful metrics
            if 'mean_intensity' in df and 'area' in df:
                df['integrated_intensity'] = df['mean_intensity'] * df['area']
            
            if 'major_axis_length' in df and 'minor_axis_length' in df:
                # Avoid division by zero for objects with no minor axis
                df['aspect_ratio'] = df['major_axis_length'] / np.where(df['minor_axis_length'] > 0, df['minor_axis_length'], np.nan)


            return {
                'status': 'success',
                'data': df,
                'message': f'Successfully extracted features from {mask.max()} objects.'
            }

        except Exception as e:
            return {'status': 'error', 'message': f'An error occurred during feature extraction: {str(e)}'}
