"""
Report Generator Module

This module provides a class to generate HTML reports from analysis data,
including population statistics, plots, and statistical test results.
"""

import pandas as pd
from typing import Dict, Any, Optional

class ReportGenerator:
    """
    Generates an HTML report from population and statistical analysis results.
    """

    def generate_report(
        self,
        population_data: pd.DataFrame,
        statistics_results: Optional[Dict[str, Any]] = None,
        dist_fig: Optional[Any] = None,
        corr_fig: Optional[Any] = None,
        box_fig: Optional[Any] = None,
        filename: str = "report.html"
    ) -> str:
        """
        Generates a complete HTML report.

        Args:
            population_data (pd.DataFrame): DataFrame with morphometric data.
            statistics_results (Optional[Dict[str, Any]]): Results from StatisticsAnalyzer.
            dist_fig (Optional[Any]): Plotly figure for distribution.
            corr_fig (Optional[Any]): Plotly figure for correlation.
            box_fig (Optional[Any]): Plotly figure for box plot comparison.
            filename (str): The name of the original file being analyzed.

        Returns:
            str: The complete HTML content of the report.
        """
        # --- 1. HTML Template ---
        html_template = """
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Analysis Report</title>
            <style>
                body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; margin: 0 auto; max-width: 1000px; padding: 20px; }}
                h1, h2, h3 {{ color: #333; }}
                .section {{ margin-bottom: 40px; border-bottom: 1px solid #eee; padding-bottom: 20px; }}
                .dataframe {{ border-collapse: collapse; width: 100%; }}
                .dataframe th, .dataframe td {{ text-align: left; padding: 8px; border: 1px solid #ddd; }}
                .dataframe th {{ background-color: #f2f2f2; }}
                .metric-box {{ display: inline-block; padding: 10px 20px; border: 1px solid #ccc; border-radius: 5px; margin-right: 15px; text-align: center;}}
                .metric-box .label {{ font-size: 0.9em; color: #666; }}
                .metric-box .value {{ font-size: 1.5em; font-weight: bold; }}
                .plot {{ margin-top: 20px; }}
            </style>
            <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
        </head>
        <body>
            <h1>Analysis Report</h1>
            <div class="section">
                <h2>Metadata</h2>
                <p><strong>Source File:</strong> {filename}</p>
                <p><strong>Report Generated:</strong> {generation_date}</p>
            </div>

            <div class="section">
                <h2>Statistical Comparison</h2>
                {statistics_section}
            </div>

            <div class="section">
                <h2>Data Summary</h2>
                <p><strong>Total Objects Analyzed:</strong> {total_objects}</p>
                {population_table}
            </div>

            <div class="section">
                <h2>Visualizations</h2>
                <h3>Group Comparison</h3>
                {box_plot}
                <h3>Feature Distributions</h3>
                {dist_plot}
                <h3>Feature Correlations</h3>
                {corr_plot}
            </div>

            <footer>
                <p><em>Report generated by the Advanced Image Biophysics Platform.</em></p>
            </footer>
        </body>
        </html>
        """

        # --- 2. Prepare Content ---
        from datetime import datetime
        generation_date = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        # Population data
        total_objects = len(population_data)
        population_table = population_data.to_html(classes='dataframe', index=False)

        # Statistics section
        stats_html = "<p>No statistical tests were performed.</p>"
        if statistics_results and statistics_results.get('status') == 'success':
            p_val = statistics_results['p_value']
            stat_val = statistics_results['statistic']
            significance = "Statistically Significant (p < 0.05)" if p_val < 0.05 else "Not Statistically Significant (p >= 0.05)"
            
            stats_html = f"""
            <div class="metric-box">
                <div class="label">P-value</div>
                <div class="value">{p_val:.4f}</div>
            </div>
            <div class="metric-box">
                <div class="label">Test Statistic</div>
                <div class="value">{stat_val:.4f}</div>
            </div>
            <h3>Conclusion: {significance}</h3>
            """
            
        # Plots
        def get_plot_html(fig):
            if fig is None:
                return "<p>Plot not generated.</p>"
            return fig.to_html(full_html=False, include_plotlyjs=False)

        box_plot_html = get_plot_html(box_fig)
        dist_plot_html = get_plot_html(dist_fig)
        corr_plot_html = get_plot_html(corr_fig)


        # --- 3. Format Final HTML ---
        report_content = html_template.format(
            filename=filename,
            generation_date=generation_date,
            statistics_section=stats_html,
            total_objects=total_objects,
            population_table=population_table,
            box_plot=box_plot_html,
            dist_plot=dist_plot_html,
            corr_plot=corr_plot_html
        )

        return report_content
