"""
Statistics Analyzer Module

This module provides a class for performing statistical comparisons on population data.
It is designed to work with pandas DataFrames generated by the PopulationAnalyzer.

It includes methods for common hypothesis tests such as the t-test, Mann-Whitney U test,
ANOVA, and the Kruskal-Wallis test, all leveraging the `scipy.stats` library.
"""

import pandas as pd
from scipy import stats
from typing import Dict, Any, List, Optional

class StatisticsAnalyzer:
    """
    Performs statistical analysis on population data.
    """

    def perform_test(self, data: pd.DataFrame, feature: str, groups: List[str], test_type: str) -> Dict[str, Any]:
        """
        Performs a selected statistical test on the given data.

        Args:
            data (pd.DataFrame): DataFrame containing the population data, including a 'group' column.
            feature (str): The name of the column (feature) to be tested.
            groups (List[str]): A list of the group names to be compared.
            test_type (str): The type of test to perform. 
                             Options: 'T-test', 'Mann-Whitney U', 'ANOVA', 'Kruskal-Wallis'.

        Returns:
            Dict[str, Any]: A dictionary containing the test statistic and the p-value.
        """
        if feature not in data.columns:
            return {'status': 'error', 'message': f'Feature "{feature}" not found in the data.'}
        
        if 'group' not in data.columns:
            return {'status': 'error', 'message': 'Group information not found in the data.'}

        # Prepare the data samples for the test
        samples = [data[feature][data['group'] == group] for group in groups]

        try:
            if test_type == 'T-test':
                if len(samples) != 2:
                    return {'status': 'error', 'message': 'T-test requires exactly two groups.'}
                stat, p_value = stats.ttest_ind(samples[0], samples[1], nan_policy='omit')
                return {'status': 'success', 'statistic': stat, 'p_value': p_value}

            elif test_type == 'Mann-Whitney U':
                if len(samples) != 2:
                    return {'status': 'error', 'message': 'Mann-Whitney U test requires exactly two groups.'}
                stat, p_value = stats.mannwhitneyu(samples[0], samples[1], alternative='two-sided')
                return {'status': 'success', 'statistic': stat, 'p_value': p_value}

            elif test_type == 'ANOVA':
                if len(samples) < 2:
                    return {'status': 'error', 'message': 'ANOVA requires at least two groups.'}
                stat, p_value = stats.f_oneway(*samples)
                return {'status': 'success', 'statistic': stat, 'p_value': p_value}

            elif test_type == 'Kruskal-Wallis':
                if len(samples) < 2:
                    return {'status': 'error', 'message': 'Kruskal-Wallis test requires at least two groups.'}
                stat, p_value = stats.kruskal(*samples)
                return {'status': 'success', 'statistic': stat, 'p_value': p_value}

            else:
                return {'status': 'error', 'message': f'Unknown test type: {test_type}'}

        except Exception as e:
            return {'status': 'error', 'message': f'An error occurred during the test: {str(e)}'}
